# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

### Comment when running locally using jekyll serve
# This would be the name of your repo
baseurl: /
# Full url including your username and repo name
url: https://albusdemens.github.io

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alberto Cereser
email: alberto.cereser@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Physicist specialised in developing image processing and data analysis algorithms. I contributed to the development of two microscopes (one from scratch!). Do you need a hand analyzing images or cruching data? Send me a line!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://albusdemens.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: albus_c
github_username: albusdemens


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Center images
kramdown:
  parse_block_html: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
